### ISSUE TITLE
Deprecate git package

### ISSUE THREAD

**Issue by mattfarina** [rancher/wrangler#249]
The git package within wrangler appears to only be used in two places and they are not using overlapping functionality. This package can be more easily maintained in those two separate places. So, this functionality should be documented as deprecated.

**Comment by mattfarina** [comment]
Note, the git package can be removed in a 2.0.0 release of wrangler but not before (so we can follow semver)

**Comment by KevinJoiner** [comment]
The git packaged has been removed from wrangler and the references have been removed from Rancher.
