### ISSUE TITLE
How to only cache a subset of the resources?

### ISSUE THREAD

**Issue by toonsevrin** [rancher/wrangler#97]
I would like my controller to only cache the secrets it controls. 

I am thus only interested in a very small subset of the secret resources. Specifically the ones with specific owner references (a custom resource is the owner).

I would also be fine with caching the relevant namespaces or labels.

**Comment by ibuildthecloud** [comment]
The only choices you have are to cache all objects in the cluster or a specific namespace.  To cache a specific namespace use the generated NewFactoryFromConfigWithNamespace method to build the controller.  Example: https://github.com/rancher/helm-controller/blob/02adbd18d6dd6874c937a35d38d088b4cc208593/main.go#L93
